export const HIDE_HEADER = 'HIDE_HEADER';
export const NOT_HIDE_HEADER = 'NOT_HIDE_HEADER';
export const CHANGE_HASHTAG = 'CHANGE_HASHTAG';
export const CHANGE_PLACE = 'CHANGE_PLACE';
export const SET_LIST_HASHTAG = 'SET_LIST_HASHTAG';
export const SET_LIST_PLACE = 'SET_LIST_PLACE';